# Generated by Django 5.0.1 on 2024-05-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('report', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='C:/Users/kayra/sınıfproje/static/img'),
        ),
    ]
